### ISSUE TITLE
undefined: syscall.SIGUSR1

### ISSUE THREAD

**Issue by Flagon00** [phikal/ijod#1]
I have this error.
resolved?

**Comment by phikal** [comment]
You mean while compiling? What version of Go and what OS are you using?

The symbol should exist, see: https://golang.org/pkg/syscall/

**Comment by Flagon00** [comment]
> You mean while compiling? What version of Go and what OS are you using?
> 
> The symbol should exist, see: https://golang.org/pkg/syscall/

Lates go1.12.7 windows/amd64

**Comment by Flagon00** [comment]
I added this manually but now i get return 0 :(
What i do wrong? 
![Adnotacja 2019-07-26 211509](https://user-images.githubusercontent.com/45333618/61976149-4ae1d400-afeb-11e9-9ef7-7ff4dc6dd779.png)

**Comment by phikal** [comment]
Oh, then I guess the issue is that Windows doesn't have the Signal [SIGUSR1](https://dsa.cs.tsinghua.edu.cn/oj/static/unix_signal.html), since Ijod wasn't built with strict cross-compatibility in mind.

If you really want to get it working, the easiest way would be to comment out the `init` function in [load.go](https://github.com/phikal/ijod/blob/master/load.go#L20), and the "syscall" import. That should be the only real Unix dependency -- but if any other issues arise, please inform me so that I can fix them.

**Comment by Flagon00** [comment]
I ran it on Ubuntu from windows store and work very well.
Nice job :)

**Comment by phikal** [comment]
Great to hear. When I get to working on cross-platform compatibility, I'll let you know.
